name: "1. Ktlint Stage"
on:
  workflow_call:
  push:
    branches: [ "ANDROID-18,19,20-TEST" ]
  pull_request:
    branches: [ "ANDROID-18,19,20-TEST" ]

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '21'

    - name: Run Detekt from gradle
      run: |
        chmod +x ./gradlew
        ./gradlew consolidateKtlintReports

    - name: Upload ktlint Report on Failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: ktlint-report
        path: /build/reports/ktlint/ktlint-report.html
