name: "2. Detekt Stage"
on:
  workflow_call:
  workflow_run:
    workflows: [ "1. Ktlint" ]
    types: [ completed ]
  push:
    branches: [ "ANDROID-18,19,20-TEST" ]
  pull_request:
    branches: [ "ANDROID-18,19,20-TEST" ]


jobs:
  detekt:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: "Run Detekt from gradle"
        run: |
          chmod +x ./gradlew
          ./gradlew detekt

      - name: Upload ktlint Report on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: detekt-report
          path: build/reports/detekt/**