name: "3. Test Stage"
on:
  workflow_call:
  push:
    branches: [ "ANDROID-18,19,20-TEST" ]
  pull_request:
    branches: [ "ANDROID-18,19,20-TEST" ]


jobs:
  test:
    if: |
      github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: | 
          chmod +x ./gradlew
          ./gradlew test

      - name: Upload test Report on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: app/build/reports/tests/testReleaseUnitTest/index.html