name: "4. Build Stage"
on:
  workflow_call:
  push:
    branches: [ "ANDROID-18,19,20" ]
  pull_request:
    branches: [ "ANDROID-18,19,20" ]


jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Debug
        run: ./gradlew assembleDebug -x consolidateKtlintReports -x detekt -x test -x lint

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-builds
          path: |
            app/build/outputs/apk/debug/app-debug.apk