name: "4. Build Stage"
on:
  push:
    branches: [ "ANDROID-18,19,20" ]
  pull_request:
    branches: [ "ANDROID-18,19,20" ]
  workflow_run:
    workflows: [ "3. Test Stage"]
        types: [completed]


jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running build debug ..."
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Debug
        run: ./gradlew build -x consolidateKtlintReports -x detekt -x test -x lint
        with:
            name: app-builds
            path: |
                app/build/outputs/apk/debug/app-debug.apk